### ISSUE TITLE
Confusion with cron entry that runs at midnight

### ISSUE THREAD

**Issue by nickmaccarthy** [josiahcarlson/parse-crontab#20]
I'm having a bit of confusion in figuring this out.  I have something that will wake up every minute ( via a linux cron job ) and figure out which "pythonic" things it needs to run via cron syntax provided by this module.  For things that are in ranges, i.e. `* 12-12 * * mon-fri`  its working fine, but for things that are static like, `0 0 * * *`, I'm having troubles when our current time meets the cron time.

Here is a code example of what I'm referring to:

```
import datetime
import pytz
from crontab import CronTab

# Run something at midnight every day
cronstr = "0 0 * * *"
now = datetime.datetime(2016, 01, 01, 00, 00, 00, 00, pytz.UTC)
print(now)
>>> 2016-01-01 00:00:00+00:00
entry = CronTab(cronstr) 
seconds_until_next_run = entry.next(now)
print(seconds_until_next_run)
>>> 86400.0
```

I would expect the value of `seconds_until_next_run` to be `0` instead of `86400`, since we are testing this at midnight at literally the same time this cron entry should match.  Checking `entry.previous(now)` results in `-86400.0` and I would think `previous` should be `0` as well. 

Is there any to accomplish what I need to do with this module?  Is possible I'm missing something ( typically the case ) , but figured I would ask anyways.

**Comment by grahambell** [comment]
There is a `test` method which you can use to see if the current minute matches.  You would need to take care of the seconds however as the time matches the cron schedule throughout a minute:

```
print(now)                                                                      
>>> 2016-01-01 00:00:59+00:00                                                  
print(entry.previous(now))                                                      
>>> -59.0                                                                      
print(entry.test(now))                                                          
>>> True
```

I do something similar to this in a cron job monitoring application:

There's a thread which sleeps a while (5s) and then steps forward from the previous time checked (in 55s jumps) looking for minutes it didn't check yet.  (So that it doesn't miss any minutes even if the regular sleep lasts a lot longer than expected). Then it tries to match the time against the cron schedule.  It does something like this:

```Python
self.schedule = CrabSchedule('0 0 * * *', ...)
self._previous = datetime.now(pytz.UTC)

while True:
    time.sleep(5)
    delta = timedelta(seconds=55)
    current = datetime.now(pytz.UTC)
    previous = self._previous

    while minute_before(previous, current):
        previous = self._previous + delta  # (previous isn't a very good name for this)

        if not minute_equal(previous, self._previous):
            if self.schedule.match(previous):
                # Do something...

        self._previous = previous
```
The actual code is at:

https://github.com/grahambell/crab/blob/master/lib/crab/service/__init__.py#L43

https://github.com/grahambell/crab/blob/master/lib/crab/service/clean.py#L37

And it uses a class `CrabSchedule` which extends `CronTab` adding a [match](https://github.com/grahambell/crab/blob/master/lib/crab/util/schedule.py#L54) method -- I wrote that before `CronTab` provided a `test` method.

**Comment by nickmaccarthy** [comment]
@grahambell thank you!  `entry.test()` is exactly what I was looking for.  I rolled my own `test()`, trying to figure out where I was by looking at `previous()` and `next()`.  I didnt see `test()`  in the documentation though, so thats why I missed it.  Thank you for the help and quick turn around, this has solved my problem!

**Comment by josiahcarlson** [comment]
Looks like this handled itself while I was out of town for work. Thank you @grahambell for the note, and thank you @nickmaccarthy for the question :)
